### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (256,256,4) (3,) (256,256,4)

### ISSUE THREAD

**Issue by ghost** [KupynOrest/RestoreGAN#9]
If you use your own data set, you will get this error.
Please tell us what to do.

Epoch 0, lr 0.0001:   0%|                                                                                    | 0/1000 [00:00<?, ?it/s]W1119 03:38:11.855473 27044 warnings.py:99] /root/anaconda3/lib/python3.7/site-packages/torch/nn/functional.py:2351: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")

W1119 03:38:12.148639 27044 warnings.py:99] /root/anaconda3/lib/python3.7/site-packages/skimage/util/arraycrop.py:177: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  cropped = ar[slices]

Epoch 0, lr 0.0001:   0%|                              | 1/1000 [00:01<18:48,  1.13s/it, loss=G_loss=3.4419; PSNR=5.4653; SSIM=0.0264]Traceback (most recent call last):
  File "train.py", line 181, in <module>
    trainer.train()
  File "train.py", line 39, in train
    self._run_epoch(epoch)
  File "train.py", line 64, in _run_epoch
    for data in tq:
  File "/root/anaconda3/lib/python3.7/site-packages/tqdm/_tqdm.py", line 937, in __iter__
    for obj in iterable:
  File "/root/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 637, in __next__
    return self._process_next_batch(batch)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 658, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/root/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 138, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/egan/restore/dataset.py", line 115, in __getitem__
    a, b = self._preprocess(a, b)
  File "/egan/restore/dataset.py", line 103, in _preprocess
    return map(transpose, self.normalize_fn(img, res))
  File "/egan/restore/aug.py", line 52, in process
    r = normalize(image=a, target=b)
  File "/root/anaconda3/lib/python3.7/site-packages/albumentations/core/composition.py", line 176, in __call__
    data = t(force_apply=force_apply, **data)
  File "/root/anaconda3/lib/python3.7/site-packages/albumentations/core/transforms_interface.py", line 87, in __call__
    return self.apply_with_params(params, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/albumentations/core/transforms_interface.py", line 100, in apply_with_params
    res[key] = target_function(arg, **dict(params, **target_dependencies))
  File "/root/anaconda3/lib/python3.7/site-packages/albumentations/augmentations/transforms.py", line 1434, in apply
    return F.normalize(image, self.mean, self.std, self.max_pixel_value)
  File "/root/anaconda3/lib/python3.7/site-packages/albumentations/augmentations/functional.py", line 141, in normalize
    img -= mean
ValueError: operands could not be broadcast together with shapes (256,256,4) (3,) (256,256,4)

**Comment by kylerioux** [comment]
Did you ever resolve this? I am facing a similar error.
